// <auto-generated />
namespace FTL_HRMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_tbl_salary_adjustment_201117 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_tbl_salary_adjustment_201117));
        
        string IMigrationMetadata.Id
        {
            get { return "201711200712510_update_tbl_salary_adjustment_201117"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
