// <auto-generated />
namespace FTL_HRMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_tbl_update_emp_parmanentDate_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_tbl_update_emp_parmanentDate_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201709100703129_update_tbl_update_emp_parmanentDate_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
