// <auto-generated />
namespace FTL_HRMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class basic_setup_by_manas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(basic_setup_by_manas));
        
        string IMigrationMetadata.Id
        {
            get { return "201708051026197_basic_setup_by_manas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
