namespace FTL_HRMS.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class update_multiple : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.tbl_BranchTransfer", "Employee_Sl", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_Employee", "Branch_Sl", "dbo.tbl_Branch");
            DropForeignKey("dbo.tbl_Employee", "Designation_Sl", "dbo.tbl_Designation");
            DropForeignKey("dbo.tbl_Education", "Employee_Sl", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_Employee", "EmployeeType_Sl", "dbo.tbl_EmployeeType");
            DropForeignKey("dbo.tbl_Experience", "Employee_Sl", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_Employee", "SourceOfHire_Sl", "dbo.tbl_SourceOfHire");
            DropForeignKey("dbo.tbl_DepartmentTransfer", "Employee_Sl", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_DisciplinaryAction", "DisciplinaryActionType_Sl", "dbo.tbl_DisciplinaryActionType");
            DropForeignKey("dbo.tbl_DisciplinaryAction", "Employee_Sl", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_LeaveHistory", "Employee_Sl", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_LeaveHistory", "LeaveType_Sl", "dbo.tbl_LeaveType");
            DropForeignKey("dbo.tbl_PerformanceRating", "Employee_Sl", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_PerformanceRating", "PerformanceIssue_Sl", "dbo.tbl_PerformanceIssue");
            DropForeignKey("dbo.tbl_Resignation", "Employee_Sl", "dbo.tbl_Employee");
            DropIndex("dbo.tbl_BranchTransfer", new[] { "Employee_Sl" });
            DropIndex("dbo.tbl_Employee", new[] { "Branch_Sl" });
            DropIndex("dbo.tbl_Employee", new[] { "Designation_Sl" });
            DropIndex("dbo.tbl_Employee", new[] { "EmployeeType_Sl" });
            DropIndex("dbo.tbl_Employee", new[] { "SourceOfHire_Sl" });
            DropIndex("dbo.tbl_Education", new[] { "Employee_Sl" });
            DropIndex("dbo.tbl_Experience", new[] { "Employee_Sl" });
            DropIndex("dbo.tbl_DepartmentTransfer", new[] { "Employee_Sl" });
            DropIndex("dbo.tbl_DisciplinaryAction", new[] { "DisciplinaryActionType_Sl" });
            DropIndex("dbo.tbl_DisciplinaryAction", new[] { "Employee_Sl" });
            DropIndex("dbo.tbl_LeaveHistory", new[] { "Employee_Sl" });
            DropIndex("dbo.tbl_LeaveHistory", new[] { "LeaveType_Sl" });
            DropIndex("dbo.tbl_PerformanceRating", new[] { "Employee_Sl" });
            DropIndex("dbo.tbl_PerformanceRating", new[] { "PerformanceIssue_Sl" });
            DropIndex("dbo.tbl_Resignation", new[] { "Employee_Sl" });
            DropColumn("dbo.tbl_BranchTransfer", "EmployeeId");
            DropColumn("dbo.tbl_Employee", "BranchId");
            DropColumn("dbo.tbl_Employee", "DesignationId");
            DropColumn("dbo.tbl_Employee", "EmployeeTypeId");
            DropColumn("dbo.tbl_Employee", "SourceOfHireId");
            DropColumn("dbo.tbl_Education", "EmployeeId");
            DropColumn("dbo.tbl_Experience", "EmployeeId");
            DropColumn("dbo.tbl_DepartmentTransfer", "EmployeeId");
            DropColumn("dbo.tbl_DisciplinaryAction", "DisciplinaryActionTypeId");
            DropColumn("dbo.tbl_DisciplinaryAction", "EmployeeId");
            DropColumn("dbo.tbl_LeaveHistory", "EmployeeId");
            DropColumn("dbo.tbl_LeaveHistory", "LeaveTypeId");
            DropColumn("dbo.tbl_PerformanceRating", "EmployeeId");
            DropColumn("dbo.tbl_PerformanceRating", "PerformanceIssueId");
            DropColumn("dbo.tbl_Resignation", "EmployeeId");
            RenameColumn(table: "dbo.tbl_BranchTransfer", name: "Employee_Sl", newName: "EmployeeId");
            RenameColumn(table: "dbo.tbl_Employee", name: "Branch_Sl", newName: "BranchId");
            RenameColumn(table: "dbo.tbl_Employee", name: "Designation_Sl", newName: "DesignationId");
            RenameColumn(table: "dbo.tbl_Education", name: "Employee_Sl", newName: "EmployeeId");
            RenameColumn(table: "dbo.tbl_Employee", name: "EmployeeType_Sl", newName: "EmployeeTypeId");
            RenameColumn(table: "dbo.tbl_Experience", name: "Employee_Sl", newName: "EmployeeId");
            RenameColumn(table: "dbo.tbl_Employee", name: "SourceOfHire_Sl", newName: "SourceOfHireId");
            RenameColumn(table: "dbo.tbl_DepartmentTransfer", name: "Employee_Sl", newName: "EmployeeId");
            RenameColumn(table: "dbo.tbl_DisciplinaryAction", name: "DisciplinaryActionType_Sl", newName: "DisciplinaryActionTypeId");
            RenameColumn(table: "dbo.tbl_DisciplinaryAction", name: "Employee_Sl", newName: "EmployeeId");
            RenameColumn(table: "dbo.tbl_LeaveHistory", name: "Employee_Sl", newName: "EmployeeId");
            RenameColumn(table: "dbo.tbl_LeaveHistory", name: "LeaveType_Sl", newName: "LeaveTypeId");
            RenameColumn(table: "dbo.tbl_PerformanceRating", name: "Employee_Sl", newName: "EmployeeId");
            RenameColumn(table: "dbo.tbl_PerformanceRating", name: "PerformanceIssue_Sl", newName: "PerformanceIssueId");
            RenameColumn(table: "dbo.tbl_Resignation", name: "Employee_Sl", newName: "EmployeeId");
            AddColumn("dbo.tbl_DepartmentTransfer", "FromDepartmentId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_DepartmentTransfer", "ToDepartmentId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_BranchTransfer", "EmployeeId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_Employee", "BranchId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_Employee", "DesignationId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_Employee", "EmployeeTypeId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_Employee", "SourceOfHireId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_Education", "EmployeeId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_Experience", "EmployeeId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_DepartmentTransfer", "EmployeeId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_DisciplinaryAction", "DisciplinaryActionTypeId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_DisciplinaryAction", "EmployeeId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_LeaveHistory", "EmployeeId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_LeaveHistory", "LeaveTypeId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_PerformanceRating", "EmployeeId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_PerformanceRating", "PerformanceIssueId", c => c.Int(nullable: false));
            AlterColumn("dbo.tbl_Resignation", "UpdatedBy", c => c.Int());
            AlterColumn("dbo.tbl_Resignation", "UpdateDate", c => c.DateTime());
            AlterColumn("dbo.tbl_Resignation", "EmployeeId", c => c.Int(nullable: false));
            CreateIndex("dbo.tbl_BranchTransfer", "EmployeeId");
            CreateIndex("dbo.tbl_Employee", "SourceOfHireId");
            CreateIndex("dbo.tbl_Employee", "DesignationId");
            CreateIndex("dbo.tbl_Employee", "EmployeeTypeId");
            CreateIndex("dbo.tbl_Employee", "BranchId");
            CreateIndex("dbo.tbl_Education", "EmployeeId");
            CreateIndex("dbo.tbl_Experience", "EmployeeId");
            CreateIndex("dbo.tbl_DepartmentTransfer", "EmployeeId");
            CreateIndex("dbo.tbl_DisciplinaryAction", "EmployeeId");
            CreateIndex("dbo.tbl_DisciplinaryAction", "DisciplinaryActionTypeId");
            CreateIndex("dbo.tbl_LeaveHistory", "EmployeeId");
            CreateIndex("dbo.tbl_LeaveHistory", "LeaveTypeId");
            CreateIndex("dbo.tbl_PerformanceRating", "EmployeeId");
            CreateIndex("dbo.tbl_PerformanceRating", "PerformanceIssueId");
            CreateIndex("dbo.tbl_Resignation", "EmployeeId");
            AddForeignKey("dbo.tbl_BranchTransfer", "EmployeeId", "dbo.tbl_Employee", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_Employee", "BranchId", "dbo.tbl_Branch", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_Employee", "DesignationId", "dbo.tbl_Designation", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_Education", "EmployeeId", "dbo.tbl_Employee", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_Employee", "EmployeeTypeId", "dbo.tbl_EmployeeType", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_Experience", "EmployeeId", "dbo.tbl_Employee", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_Employee", "SourceOfHireId", "dbo.tbl_SourceOfHire", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_DepartmentTransfer", "EmployeeId", "dbo.tbl_Employee", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_DisciplinaryAction", "DisciplinaryActionTypeId", "dbo.tbl_DisciplinaryActionType", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_DisciplinaryAction", "EmployeeId", "dbo.tbl_Employee", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_LeaveHistory", "EmployeeId", "dbo.tbl_Employee", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_LeaveHistory", "LeaveTypeId", "dbo.tbl_LeaveType", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_PerformanceRating", "EmployeeId", "dbo.tbl_Employee", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_PerformanceRating", "PerformanceIssueId", "dbo.tbl_PerformanceIssue", "Sl", cascadeDelete: true);
            AddForeignKey("dbo.tbl_Resignation", "EmployeeId", "dbo.tbl_Employee", "Sl", cascadeDelete: true);
            DropColumn("dbo.tbl_DepartmentTransfer", "FromDesignationId");
            DropColumn("dbo.tbl_DepartmentTransfer", "ToDesignationId");
        }
        
        public override void Down()
        {
            AddColumn("dbo.tbl_DepartmentTransfer", "ToDesignationId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_DepartmentTransfer", "FromDesignationId", c => c.Int(nullable: false));
            DropForeignKey("dbo.tbl_Resignation", "EmployeeId", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_PerformanceRating", "PerformanceIssueId", "dbo.tbl_PerformanceIssue");
            DropForeignKey("dbo.tbl_PerformanceRating", "EmployeeId", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_LeaveHistory", "LeaveTypeId", "dbo.tbl_LeaveType");
            DropForeignKey("dbo.tbl_LeaveHistory", "EmployeeId", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_DisciplinaryAction", "EmployeeId", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_DisciplinaryAction", "DisciplinaryActionTypeId", "dbo.tbl_DisciplinaryActionType");
            DropForeignKey("dbo.tbl_DepartmentTransfer", "EmployeeId", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_Employee", "SourceOfHireId", "dbo.tbl_SourceOfHire");
            DropForeignKey("dbo.tbl_Experience", "EmployeeId", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_Employee", "EmployeeTypeId", "dbo.tbl_EmployeeType");
            DropForeignKey("dbo.tbl_Education", "EmployeeId", "dbo.tbl_Employee");
            DropForeignKey("dbo.tbl_Employee", "DesignationId", "dbo.tbl_Designation");
            DropForeignKey("dbo.tbl_Employee", "BranchId", "dbo.tbl_Branch");
            DropForeignKey("dbo.tbl_BranchTransfer", "EmployeeId", "dbo.tbl_Employee");
            DropIndex("dbo.tbl_Resignation", new[] { "EmployeeId" });
            DropIndex("dbo.tbl_PerformanceRating", new[] { "PerformanceIssueId" });
            DropIndex("dbo.tbl_PerformanceRating", new[] { "EmployeeId" });
            DropIndex("dbo.tbl_LeaveHistory", new[] { "LeaveTypeId" });
            DropIndex("dbo.tbl_LeaveHistory", new[] { "EmployeeId" });
            DropIndex("dbo.tbl_DisciplinaryAction", new[] { "DisciplinaryActionTypeId" });
            DropIndex("dbo.tbl_DisciplinaryAction", new[] { "EmployeeId" });
            DropIndex("dbo.tbl_DepartmentTransfer", new[] { "EmployeeId" });
            DropIndex("dbo.tbl_Experience", new[] { "EmployeeId" });
            DropIndex("dbo.tbl_Education", new[] { "EmployeeId" });
            DropIndex("dbo.tbl_Employee", new[] { "BranchId" });
            DropIndex("dbo.tbl_Employee", new[] { "EmployeeTypeId" });
            DropIndex("dbo.tbl_Employee", new[] { "DesignationId" });
            DropIndex("dbo.tbl_Employee", new[] { "SourceOfHireId" });
            DropIndex("dbo.tbl_BranchTransfer", new[] { "EmployeeId" });
            AlterColumn("dbo.tbl_Resignation", "EmployeeId", c => c.Int());
            AlterColumn("dbo.tbl_Resignation", "UpdateDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.tbl_Resignation", "UpdatedBy", c => c.String());
            AlterColumn("dbo.tbl_PerformanceRating", "PerformanceIssueId", c => c.Int());
            AlterColumn("dbo.tbl_PerformanceRating", "EmployeeId", c => c.Int());
            AlterColumn("dbo.tbl_LeaveHistory", "LeaveTypeId", c => c.Int());
            AlterColumn("dbo.tbl_LeaveHistory", "EmployeeId", c => c.Int());
            AlterColumn("dbo.tbl_DisciplinaryAction", "EmployeeId", c => c.Int());
            AlterColumn("dbo.tbl_DisciplinaryAction", "DisciplinaryActionTypeId", c => c.Int());
            AlterColumn("dbo.tbl_DepartmentTransfer", "EmployeeId", c => c.Int());
            AlterColumn("dbo.tbl_Experience", "EmployeeId", c => c.Int());
            AlterColumn("dbo.tbl_Education", "EmployeeId", c => c.Int());
            AlterColumn("dbo.tbl_Employee", "SourceOfHireId", c => c.Int());
            AlterColumn("dbo.tbl_Employee", "EmployeeTypeId", c => c.Int());
            AlterColumn("dbo.tbl_Employee", "DesignationId", c => c.Int());
            AlterColumn("dbo.tbl_Employee", "BranchId", c => c.Int());
            AlterColumn("dbo.tbl_BranchTransfer", "EmployeeId", c => c.Int());
            DropColumn("dbo.tbl_DepartmentTransfer", "ToDepartmentId");
            DropColumn("dbo.tbl_DepartmentTransfer", "FromDepartmentId");
            RenameColumn(table: "dbo.tbl_Resignation", name: "EmployeeId", newName: "Employee_Sl");
            RenameColumn(table: "dbo.tbl_PerformanceRating", name: "PerformanceIssueId", newName: "PerformanceIssue_Sl");
            RenameColumn(table: "dbo.tbl_PerformanceRating", name: "EmployeeId", newName: "Employee_Sl");
            RenameColumn(table: "dbo.tbl_LeaveHistory", name: "LeaveTypeId", newName: "LeaveType_Sl");
            RenameColumn(table: "dbo.tbl_LeaveHistory", name: "EmployeeId", newName: "Employee_Sl");
            RenameColumn(table: "dbo.tbl_DisciplinaryAction", name: "EmployeeId", newName: "Employee_Sl");
            RenameColumn(table: "dbo.tbl_DisciplinaryAction", name: "DisciplinaryActionTypeId", newName: "DisciplinaryActionType_Sl");
            RenameColumn(table: "dbo.tbl_DepartmentTransfer", name: "EmployeeId", newName: "Employee_Sl");
            RenameColumn(table: "dbo.tbl_Employee", name: "SourceOfHireId", newName: "SourceOfHire_Sl");
            RenameColumn(table: "dbo.tbl_Experience", name: "EmployeeId", newName: "Employee_Sl");
            RenameColumn(table: "dbo.tbl_Employee", name: "EmployeeTypeId", newName: "EmployeeType_Sl");
            RenameColumn(table: "dbo.tbl_Education", name: "EmployeeId", newName: "Employee_Sl");
            RenameColumn(table: "dbo.tbl_Employee", name: "DesignationId", newName: "Designation_Sl");
            RenameColumn(table: "dbo.tbl_Employee", name: "BranchId", newName: "Branch_Sl");
            RenameColumn(table: "dbo.tbl_BranchTransfer", name: "EmployeeId", newName: "Employee_Sl");
            AddColumn("dbo.tbl_Resignation", "EmployeeId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_PerformanceRating", "PerformanceIssueId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_PerformanceRating", "EmployeeId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_LeaveHistory", "LeaveTypeId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_LeaveHistory", "EmployeeId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_DisciplinaryAction", "EmployeeId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_DisciplinaryAction", "DisciplinaryActionTypeId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_DepartmentTransfer", "EmployeeId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_Experience", "EmployeeId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_Education", "EmployeeId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_Employee", "SourceOfHireId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_Employee", "EmployeeTypeId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_Employee", "DesignationId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_Employee", "BranchId", c => c.Int(nullable: false));
            AddColumn("dbo.tbl_BranchTransfer", "EmployeeId", c => c.Int(nullable: false));
            CreateIndex("dbo.tbl_Resignation", "Employee_Sl");
            CreateIndex("dbo.tbl_PerformanceRating", "PerformanceIssue_Sl");
            CreateIndex("dbo.tbl_PerformanceRating", "Employee_Sl");
            CreateIndex("dbo.tbl_LeaveHistory", "LeaveType_Sl");
            CreateIndex("dbo.tbl_LeaveHistory", "Employee_Sl");
            CreateIndex("dbo.tbl_DisciplinaryAction", "Employee_Sl");
            CreateIndex("dbo.tbl_DisciplinaryAction", "DisciplinaryActionType_Sl");
            CreateIndex("dbo.tbl_DepartmentTransfer", "Employee_Sl");
            CreateIndex("dbo.tbl_Experience", "Employee_Sl");
            CreateIndex("dbo.tbl_Education", "Employee_Sl");
            CreateIndex("dbo.tbl_Employee", "SourceOfHire_Sl");
            CreateIndex("dbo.tbl_Employee", "EmployeeType_Sl");
            CreateIndex("dbo.tbl_Employee", "Designation_Sl");
            CreateIndex("dbo.tbl_Employee", "Branch_Sl");
            CreateIndex("dbo.tbl_BranchTransfer", "Employee_Sl");
            AddForeignKey("dbo.tbl_Resignation", "Employee_Sl", "dbo.tbl_Employee", "Sl");
            AddForeignKey("dbo.tbl_PerformanceRating", "PerformanceIssue_Sl", "dbo.tbl_PerformanceIssue", "Sl");
            AddForeignKey("dbo.tbl_PerformanceRating", "Employee_Sl", "dbo.tbl_Employee", "Sl");
            AddForeignKey("dbo.tbl_LeaveHistory", "LeaveType_Sl", "dbo.tbl_LeaveType", "Sl");
            AddForeignKey("dbo.tbl_LeaveHistory", "Employee_Sl", "dbo.tbl_Employee", "Sl");
            AddForeignKey("dbo.tbl_DisciplinaryAction", "Employee_Sl", "dbo.tbl_Employee", "Sl");
            AddForeignKey("dbo.tbl_DisciplinaryAction", "DisciplinaryActionType_Sl", "dbo.tbl_DisciplinaryActionType", "Sl");
            AddForeignKey("dbo.tbl_DepartmentTransfer", "Employee_Sl", "dbo.tbl_Employee", "Sl");
            AddForeignKey("dbo.tbl_Employee", "SourceOfHire_Sl", "dbo.tbl_SourceOfHire", "Sl");
            AddForeignKey("dbo.tbl_Experience", "Employee_Sl", "dbo.tbl_Employee", "Sl");
            AddForeignKey("dbo.tbl_Employee", "EmployeeType_Sl", "dbo.tbl_EmployeeType", "Sl");
            AddForeignKey("dbo.tbl_Education", "Employee_Sl", "dbo.tbl_Employee", "Sl");
            AddForeignKey("dbo.tbl_Employee", "Designation_Sl", "dbo.tbl_Designation", "Sl");
            AddForeignKey("dbo.tbl_Employee", "Branch_Sl", "dbo.tbl_Branch", "Sl");
            AddForeignKey("dbo.tbl_BranchTransfer", "Employee_Sl", "dbo.tbl_Employee", "Sl");
        }
    }
}
