// <auto-generated />
namespace FTL_HRMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_tbl_monthlyattendance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_tbl_monthlyattendance));
        
        string IMigrationMetadata.Id
        {
            get { return "201709161039441_update_tbl_monthlyattendance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
