// <auto-generated />
namespace FTL_HRMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_tbl_PromotionHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tbl_PromotionHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201709101206532_add_tbl_PromotionHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
